---
title: "Data MD1"
author: "Julie Norman"
date: "2/3/2019"
output: html_document
---

#Library

```{r}
library(readxl)
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)

```

# Harrasment reports 

```{r}
EEOCdf <- read_excel("SH Charge Receipts.xlsx")
#View(SH_Charge_Receipts)
```

```{r}
EEOCdf$DATE <- EEOCdf$CHARGE_FILING_DATE
```


```{r}
EEOCdf$CHARGE_FILING_DATE <- as.Date.POSIXct(EEOCdf$CHARGE_FILING_DATE, "%Y-%m-%d", tz = "GMT")
```

```{r}
EEOCdf$DATEym <- format(EEOCdf$DATE, "%Y-%m")
str(EEOCdf$DATEym)
```


buzzfeed github
https://github.com/BuzzFeedNews/2017-12-eeoc-harassment-charges 


## Clean

```{r}
selectdf <- select(EEOCdf, CHARGE_FILING_DATE, R_NUMBER_OF_EMPLOYEES, R_TYPE, DATE, DATEym, CP_SEX)

```

### Complaintant Sex
```{r}
sex<- table(selectdf$DATEym, selectdf$CP_SEX)

sexdf<- as.data.frame(sex)
sexdf <- reshape(sexdf, idvar = "Var1", timevar = "Var2", direction = "wide")
```

### R_TYPE
```{r}
firmtype<- table(selectdf$DATEym, selectdf$R_TYPE)

firmtypedf<- as.data.frame(firmtype)
firmtypedf <- reshape(firmtypedf, idvar = "Var1", timevar = "Var2", direction = "wide")


```

### R_NUMBER_OF_EMPLOYEES 

```{r}
firmsize <- table(selectdf$DATEym, selectdf$R_NUMBER_OF_EMPLOYEES)

firmsizedf<- as.data.frame(firmsize)
firmsizedf <- reshape(firmsizedf, idvar = "Var1", timevar = "Var2", direction = "wide")
```


##Merge

```{r}
merge1df <- merge(firmsizedf, firmtypedf, by = "Var1")

merge2df <- merge(merge1df, sexdf, by = "Var1")

names(merge2df)
```

### rename variables

```{r}
colnames(merge2df)[colnames(merge2df) == "Var1"] <- "DATEym"



merge2df$Count.Report <- merge2df$`Freq.CP Sex Not Available/Applicable`+ merge2df$Freq.Female + merge2df$Freq.Male +merge2df$Freq.NULL

merge2df$prop.fem <- merge2df$Freq.Female/merge2df$Count.Report

merge2df$prop.priv <- ( merge2df$`Freq.Private College/University` + merge2df$`Freq.Private College/University (Inactive Code)` + merge2df$`Freq.Private Elem/Secondary School` + merge2df$`Freq.Private Employer` + merge2df$`Freq.Private Employment Agency` )/merge2df$Count.Report



```




# Labor Market Conditions Index
## Labor Market Momentum Index

```{r}

LMCIdf <- read.csv("FRBKCLMCIM.csv")

LMCIdf
```


```{r}
LMCIdf$DATE <- as.Date(LMCIdf$DATE, "%Y-%m-%d")

LMCIdf$DATEym <- format(LMCIdf$DATE, "%Y-%m")
```

https://fred.stlouisfed.org/series/FRBKCLMCIM


# Civilian Employment Rate

```{r}
EMPLRTdf <- read.csv("LREM25TTUSM156S.csv")

str(EMPLRTdf)
```

```{r}
EMPLRTdf$DATE <- as.Date(EMPLRTdf$DATE, "%Y-%m-%d")

EMPLRTdf %>% filter(EMPLRTdf$DATE >= "1995-01-01") 



EMPLRTdf$DATEym <- format(EMPLRTdf$DATE, "%Y-%m")
```

employment rate 

https://fred.stlouisfed.org/series/LREM25TTUSM156S#

# Join

```{r}

finaldf <- list(merge2df, LMCIdf, EMPLRTdf) %>% 
 reduce(left_join, by = "DATEym") 

head(finaldf)
```



# Clean Variables
```{r}
#Redundent
finaldf$DATE.y <- NULL

#Irrelevant 
finaldf$Freq.NULL.x <- NULL
finaldf$Freq.NULL.y <- NULL
finaldf$Freq.NULL <- NULL

#Ambiguous
names(finaldf)[names(finaldf) == 'Freq.Other'] <- 'Freq.Other Firm Type'
names(finaldf)[names(finaldf) == 'LREM25TTUSM156S'] <- 'CivEmployRate'
names(finaldf)[names(finaldf) == 'FRBKCLMCIM'] <- 'LaborMomen'

head(finaldf)
```




```{r}
write.csv(finaldf, file = "MD1export.csv")
```

















