---
title: "Seasonal Adjust"
author: "Julie Norman"
date: "3/16/2019"
output: html_document
---

# Library

```{r}
library("TTR")
library("readr")
library("zoo") 
library("dplyr")
library("lubridate")
library("plyr")
```

# Upload

```{r}
df <- read.csv("MD1export.csv")
str(df)
```

coding via: https://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/ 

# Plot

```{r}
tsdf <- ts(df$Count.Report, frequency = 12, start = c(1995, 10))
```

```{r}
plot.ts(tsdf)
```

# Data Transformation

## Log

```{r}
lgts_df <- log(tsdf)
plot.ts(lgts_df)
```

## Smoothing

```{r}
lgts20_df <- SMA(lgts_df, n = 20)
plot.ts(lgts20_df)
```

## Decompose

```{r}
compts_df <- decompose(tsdf)

compts_df$seasonal
```


```{r}
plot(compts_df)
```

# Seasonal Adjustment

```{r}
adjts <- (tsdf - compts_df$seasonal)

plot.ts(adjts)


```

# Data Cleaning

## Extract Dates/Rows

```{r}
# seasonally adjusted reports

adjts_df <- as.data.frame(adjts)

adjts_df$X1 <- seq.int(nrow(adjts_df))

# Dates

DATEymd <- as.Date(as.yearmon(time(adjts)))



DATEymd_df <- as.data.frame(DATEymd)

DATEymd_df$X1 <- seq.int(nrow(DATEymd_df))


```


## Join 

```{r}

seasadj_df <- full_join(DATEymd_df, adjts_df, by = "X1")

names(seasadj_df)[names(seasadj_df) == 'x'] <- 'SeasCount.Report'

str(seasadj_df)

```

## Join to original data


```{r}
df$X1 <- df$X


finalSdf <- join(df, seasadj_df, by = "X1")



```

## Delete Redundent Columns

```{r}
finalSdf$DATE.x <- NULL

str(finalSdf)
```


# Export 

```{r}
write.csv(finalSdf, file = "MD3export.csv")
```






